#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thuVienControls
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="qlktx")]
	public partial class QL_KTXDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDanhMucManHinh(DanhMucManHinh instance);
    partial void UpdateDanhMucManHinh(DanhMucManHinh instance);
    partial void DeleteDanhMucManHinh(DanhMucManHinh instance);
    partial void InsertGiaDien(GiaDien instance);
    partial void UpdateGiaDien(GiaDien instance);
    partial void DeleteGiaDien(GiaDien instance);
    partial void InsertGiaNuoc(GiaNuoc instance);
    partial void UpdateGiaNuoc(GiaNuoc instance);
    partial void DeleteGiaNuoc(GiaNuoc instance);
    partial void InsertHoaDonDienNuoc(HoaDonDienNuoc instance);
    partial void UpdateHoaDonDienNuoc(HoaDonDienNuoc instance);
    partial void DeleteHoaDonDienNuoc(HoaDonDienNuoc instance);
    partial void InsertHopDongThuePhong(HopDongThuePhong instance);
    partial void UpdateHopDongThuePhong(HopDongThuePhong instance);
    partial void DeleteHopDongThuePhong(HopDongThuePhong instance);
    partial void InsertLoaiPhong(LoaiPhong instance);
    partial void UpdateLoaiPhong(LoaiPhong instance);
    partial void DeleteLoaiPhong(LoaiPhong instance);
    partial void InsertNguoiDung(NguoiDung instance);
    partial void UpdateNguoiDung(NguoiDung instance);
    partial void DeleteNguoiDung(NguoiDung instance);
    partial void InsertPhong(Phong instance);
    partial void UpdatePhong(Phong instance);
    partial void DeletePhong(Phong instance);
    partial void InsertSinhVien(SinhVien instance);
    partial void UpdateSinhVien(SinhVien instance);
    partial void DeleteSinhVien(SinhVien instance);
    partial void InsertSuCo(SuCo instance);
    partial void UpdateSuCo(SuCo instance);
    partial void DeleteSuCo(SuCo instance);
    partial void InsertVaiTro(VaiTro instance);
    partial void UpdateVaiTro(VaiTro instance);
    partial void DeleteVaiTro(VaiTro instance);
    #endregion
		
		public QL_KTXDataContext() : 
				base(global::thuVienControls.Properties.Settings.Default.qlktxConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QL_KTXDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QL_KTXDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QL_KTXDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QL_KTXDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DanhMucManHinh> DanhMucManHinhs
		{
			get
			{
				return this.GetTable<DanhMucManHinh>();
			}
		}
		
		public System.Data.Linq.Table<GiaDien> GiaDiens
		{
			get
			{
				return this.GetTable<GiaDien>();
			}
		}
		
		public System.Data.Linq.Table<GiaNuoc> GiaNuocs
		{
			get
			{
				return this.GetTable<GiaNuoc>();
			}
		}
		
		public System.Data.Linq.Table<HoaDonDienNuoc> HoaDonDienNuocs
		{
			get
			{
				return this.GetTable<HoaDonDienNuoc>();
			}
		}
		
		public System.Data.Linq.Table<HopDongThuePhong> HopDongThuePhongs
		{
			get
			{
				return this.GetTable<HopDongThuePhong>();
			}
		}
		
		public System.Data.Linq.Table<LoaiPhong> LoaiPhongs
		{
			get
			{
				return this.GetTable<LoaiPhong>();
			}
		}
		
		public System.Data.Linq.Table<NguoiDung> NguoiDungs
		{
			get
			{
				return this.GetTable<NguoiDung>();
			}
		}
		
		public System.Data.Linq.Table<PhanQuyen> PhanQuyens
		{
			get
			{
				return this.GetTable<PhanQuyen>();
			}
		}
		
		public System.Data.Linq.Table<Phong> Phongs
		{
			get
			{
				return this.GetTable<Phong>();
			}
		}
		
		public System.Data.Linq.Table<SinhVien> SinhViens
		{
			get
			{
				return this.GetTable<SinhVien>();
			}
		}
		
		public System.Data.Linq.Table<SuCo> SuCos
		{
			get
			{
				return this.GetTable<SuCo>();
			}
		}
		
		public System.Data.Linq.Table<VaiTro> VaiTros
		{
			get
			{
				return this.GetTable<VaiTro>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DanhMucManHinh")]
	public partial class DanhMucManHinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Ma_Man_Hinh;
		
		private string _Ten_Man_Hinh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_Man_HinhChanging(int value);
    partial void OnMa_Man_HinhChanged();
    partial void OnTen_Man_HinhChanging(string value);
    partial void OnTen_Man_HinhChanged();
    #endregion
		
		public DanhMucManHinh()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Man_Hinh", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Ma_Man_Hinh
		{
			get
			{
				return this._Ma_Man_Hinh;
			}
			set
			{
				if ((this._Ma_Man_Hinh != value))
				{
					this.OnMa_Man_HinhChanging(value);
					this.SendPropertyChanging();
					this._Ma_Man_Hinh = value;
					this.SendPropertyChanged("Ma_Man_Hinh");
					this.OnMa_Man_HinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_Man_Hinh", DbType="NVarChar(50)")]
		public string Ten_Man_Hinh
		{
			get
			{
				return this._Ten_Man_Hinh;
			}
			set
			{
				if ((this._Ten_Man_Hinh != value))
				{
					this.OnTen_Man_HinhChanging(value);
					this.SendPropertyChanging();
					this._Ten_Man_Hinh = value;
					this.SendPropertyChanged("Ten_Man_Hinh");
					this.OnTen_Man_HinhChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GiaDien")]
	public partial class GiaDien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _so_bat_dau;
		
		private System.Nullable<decimal> _Gia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void Onso_bat_dauChanging(System.Nullable<int> value);
    partial void Onso_bat_dauChanged();
    partial void OnGiaChanging(System.Nullable<decimal> value);
    partial void OnGiaChanged();
    #endregion
		
		public GiaDien()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_bat_dau", DbType="Int")]
		public System.Nullable<int> so_bat_dau
		{
			get
			{
				return this._so_bat_dau;
			}
			set
			{
				if ((this._so_bat_dau != value))
				{
					this.Onso_bat_dauChanging(value);
					this.SendPropertyChanging();
					this._so_bat_dau = value;
					this.SendPropertyChanged("so_bat_dau");
					this.Onso_bat_dauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Decimal(10,3)")]
		public System.Nullable<decimal> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GiaNuoc")]
	public partial class GiaNuoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<decimal> _Gia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnGiaChanging(System.Nullable<decimal> value);
    partial void OnGiaChanged();
    #endregion
		
		public GiaNuoc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Decimal(10,3)")]
		public System.Nullable<decimal> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaDonDienNuoc")]
	public partial class HoaDonDienNuoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _hoa_don_id;
		
		private System.Nullable<int> _phong_id;
		
		private System.Nullable<int> _thang;
		
		private System.Nullable<int> _nam;
		
		private System.Nullable<int> _so_dien;
		
		private System.Nullable<int> _so_khoi_nuoc;
		
		private System.Nullable<decimal> _tong_tien;
		
		private string _trang_thai;
		
		private EntityRef<Phong> _Phong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onhoa_don_idChanging(int value);
    partial void Onhoa_don_idChanged();
    partial void Onphong_idChanging(System.Nullable<int> value);
    partial void Onphong_idChanged();
    partial void OnthangChanging(System.Nullable<int> value);
    partial void OnthangChanged();
    partial void OnnamChanging(System.Nullable<int> value);
    partial void OnnamChanged();
    partial void Onso_dienChanging(System.Nullable<int> value);
    partial void Onso_dienChanged();
    partial void Onso_khoi_nuocChanging(System.Nullable<int> value);
    partial void Onso_khoi_nuocChanged();
    partial void Ontong_tienChanging(System.Nullable<decimal> value);
    partial void Ontong_tienChanged();
    partial void Ontrang_thaiChanging(string value);
    partial void Ontrang_thaiChanged();
    #endregion
		
		public HoaDonDienNuoc()
		{
			this._Phong = default(EntityRef<Phong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoa_don_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int hoa_don_id
		{
			get
			{
				return this._hoa_don_id;
			}
			set
			{
				if ((this._hoa_don_id != value))
				{
					this.Onhoa_don_idChanging(value);
					this.SendPropertyChanging();
					this._hoa_don_id = value;
					this.SendPropertyChanged("hoa_don_id");
					this.Onhoa_don_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phong_id", DbType="Int")]
		public System.Nullable<int> phong_id
		{
			get
			{
				return this._phong_id;
			}
			set
			{
				if ((this._phong_id != value))
				{
					if (this._Phong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onphong_idChanging(value);
					this.SendPropertyChanging();
					this._phong_id = value;
					this.SendPropertyChanged("phong_id");
					this.Onphong_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thang", DbType="Int")]
		public System.Nullable<int> thang
		{
			get
			{
				return this._thang;
			}
			set
			{
				if ((this._thang != value))
				{
					this.OnthangChanging(value);
					this.SendPropertyChanging();
					this._thang = value;
					this.SendPropertyChanged("thang");
					this.OnthangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nam", DbType="Int")]
		public System.Nullable<int> nam
		{
			get
			{
				return this._nam;
			}
			set
			{
				if ((this._nam != value))
				{
					this.OnnamChanging(value);
					this.SendPropertyChanging();
					this._nam = value;
					this.SendPropertyChanged("nam");
					this.OnnamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_dien", DbType="Int")]
		public System.Nullable<int> so_dien
		{
			get
			{
				return this._so_dien;
			}
			set
			{
				if ((this._so_dien != value))
				{
					this.Onso_dienChanging(value);
					this.SendPropertyChanging();
					this._so_dien = value;
					this.SendPropertyChanged("so_dien");
					this.Onso_dienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_khoi_nuoc", DbType="Int")]
		public System.Nullable<int> so_khoi_nuoc
		{
			get
			{
				return this._so_khoi_nuoc;
			}
			set
			{
				if ((this._so_khoi_nuoc != value))
				{
					this.Onso_khoi_nuocChanging(value);
					this.SendPropertyChanging();
					this._so_khoi_nuoc = value;
					this.SendPropertyChanged("so_khoi_nuoc");
					this.Onso_khoi_nuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tong_tien", DbType="Decimal(10,3)")]
		public System.Nullable<decimal> tong_tien
		{
			get
			{
				return this._tong_tien;
			}
			set
			{
				if ((this._tong_tien != value))
				{
					this.Ontong_tienChanging(value);
					this.SendPropertyChanging();
					this._tong_tien = value;
					this.SendPropertyChanged("tong_tien");
					this.Ontong_tienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trang_thai", DbType="NVarChar(30)")]
		public string trang_thai
		{
			get
			{
				return this._trang_thai;
			}
			set
			{
				if ((this._trang_thai != value))
				{
					this.Ontrang_thaiChanging(value);
					this.SendPropertyChanging();
					this._trang_thai = value;
					this.SendPropertyChanged("trang_thai");
					this.Ontrang_thaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phong_HoaDonDienNuoc", Storage="_Phong", ThisKey="phong_id", OtherKey="phong_id", IsForeignKey=true)]
		public Phong Phong
		{
			get
			{
				return this._Phong.Entity;
			}
			set
			{
				Phong previousValue = this._Phong.Entity;
				if (((previousValue != value) 
							|| (this._Phong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Phong.Entity = null;
						previousValue.HoaDonDienNuocs.Remove(this);
					}
					this._Phong.Entity = value;
					if ((value != null))
					{
						value.HoaDonDienNuocs.Add(this);
						this._phong_id = value.phong_id;
					}
					else
					{
						this._phong_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Phong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HopDongThuePhong")]
	public partial class HopDongThuePhong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _hop_dong_id;
		
		private System.Nullable<int> _phong_id;
		
		private System.Nullable<int> _sinh_vien_id;
		
		private System.Nullable<System.DateTime> _ngay_lap;
		
		private System.Nullable<System.DateTime> _ngay_bat_dau_thue;
		
		private System.Nullable<System.DateTime> _ngay_ket_thuc_thue;
		
		private string _trangthai;
		
		private System.Nullable<int> _tienthu;
		
		private EntityRef<Phong> _Phong;
		
		private EntityRef<SinhVien> _SinhVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onhop_dong_idChanging(int value);
    partial void Onhop_dong_idChanged();
    partial void Onphong_idChanging(System.Nullable<int> value);
    partial void Onphong_idChanged();
    partial void Onsinh_vien_idChanging(System.Nullable<int> value);
    partial void Onsinh_vien_idChanged();
    partial void Onngay_lapChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_lapChanged();
    partial void Onngay_bat_dau_thueChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_bat_dau_thueChanged();
    partial void Onngay_ket_thuc_thueChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_ket_thuc_thueChanged();
    partial void OntrangthaiChanging(string value);
    partial void OntrangthaiChanged();
    partial void OntienthuChanging(System.Nullable<int> value);
    partial void OntienthuChanged();
    #endregion
		
		public HopDongThuePhong()
		{
			this._Phong = default(EntityRef<Phong>);
			this._SinhVien = default(EntityRef<SinhVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hop_dong_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int hop_dong_id
		{
			get
			{
				return this._hop_dong_id;
			}
			set
			{
				if ((this._hop_dong_id != value))
				{
					this.Onhop_dong_idChanging(value);
					this.SendPropertyChanging();
					this._hop_dong_id = value;
					this.SendPropertyChanged("hop_dong_id");
					this.Onhop_dong_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phong_id", DbType="Int")]
		public System.Nullable<int> phong_id
		{
			get
			{
				return this._phong_id;
			}
			set
			{
				if ((this._phong_id != value))
				{
					if (this._Phong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onphong_idChanging(value);
					this.SendPropertyChanging();
					this._phong_id = value;
					this.SendPropertyChanged("phong_id");
					this.Onphong_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sinh_vien_id", DbType="Int")]
		public System.Nullable<int> sinh_vien_id
		{
			get
			{
				return this._sinh_vien_id;
			}
			set
			{
				if ((this._sinh_vien_id != value))
				{
					if (this._SinhVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsinh_vien_idChanging(value);
					this.SendPropertyChanging();
					this._sinh_vien_id = value;
					this.SendPropertyChanged("sinh_vien_id");
					this.Onsinh_vien_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_lap", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_lap
		{
			get
			{
				return this._ngay_lap;
			}
			set
			{
				if ((this._ngay_lap != value))
				{
					this.Onngay_lapChanging(value);
					this.SendPropertyChanging();
					this._ngay_lap = value;
					this.SendPropertyChanged("ngay_lap");
					this.Onngay_lapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_bat_dau_thue", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_bat_dau_thue
		{
			get
			{
				return this._ngay_bat_dau_thue;
			}
			set
			{
				if ((this._ngay_bat_dau_thue != value))
				{
					this.Onngay_bat_dau_thueChanging(value);
					this.SendPropertyChanging();
					this._ngay_bat_dau_thue = value;
					this.SendPropertyChanged("ngay_bat_dau_thue");
					this.Onngay_bat_dau_thueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_ket_thuc_thue", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_ket_thuc_thue
		{
			get
			{
				return this._ngay_ket_thuc_thue;
			}
			set
			{
				if ((this._ngay_ket_thuc_thue != value))
				{
					this.Onngay_ket_thuc_thueChanging(value);
					this.SendPropertyChanging();
					this._ngay_ket_thuc_thue = value;
					this.SendPropertyChanged("ngay_ket_thuc_thue");
					this.Onngay_ket_thuc_thueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangthai", DbType="NVarChar(50)")]
		public string trangthai
		{
			get
			{
				return this._trangthai;
			}
			set
			{
				if ((this._trangthai != value))
				{
					this.OntrangthaiChanging(value);
					this.SendPropertyChanging();
					this._trangthai = value;
					this.SendPropertyChanged("trangthai");
					this.OntrangthaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tienthu", DbType="Int")]
		public System.Nullable<int> tienthu
		{
			get
			{
				return this._tienthu;
			}
			set
			{
				if ((this._tienthu != value))
				{
					this.OntienthuChanging(value);
					this.SendPropertyChanging();
					this._tienthu = value;
					this.SendPropertyChanged("tienthu");
					this.OntienthuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phong_HopDongThuePhong", Storage="_Phong", ThisKey="phong_id", OtherKey="phong_id", IsForeignKey=true)]
		public Phong Phong
		{
			get
			{
				return this._Phong.Entity;
			}
			set
			{
				Phong previousValue = this._Phong.Entity;
				if (((previousValue != value) 
							|| (this._Phong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Phong.Entity = null;
						previousValue.HopDongThuePhongs.Remove(this);
					}
					this._Phong.Entity = value;
					if ((value != null))
					{
						value.HopDongThuePhongs.Add(this);
						this._phong_id = value.phong_id;
					}
					else
					{
						this._phong_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Phong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SinhVien_HopDongThuePhong", Storage="_SinhVien", ThisKey="sinh_vien_id", OtherKey="sinh_vien_id", IsForeignKey=true)]
		public SinhVien SinhVien
		{
			get
			{
				return this._SinhVien.Entity;
			}
			set
			{
				SinhVien previousValue = this._SinhVien.Entity;
				if (((previousValue != value) 
							|| (this._SinhVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SinhVien.Entity = null;
						previousValue.HopDongThuePhongs.Remove(this);
					}
					this._SinhVien.Entity = value;
					if ((value != null))
					{
						value.HopDongThuePhongs.Add(this);
						this._sinh_vien_id = value.sinh_vien_id;
					}
					else
					{
						this._sinh_vien_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("SinhVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiPhong")]
	public partial class LoaiPhong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _loai_phong_id;
		
		private string _ten_loai_phong;
		
		private System.Nullable<decimal> _gia_phong;
		
		private System.Nullable<int> _so_nguoi_toi_da;
		
		private EntitySet<Phong> _Phongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onloai_phong_idChanging(int value);
    partial void Onloai_phong_idChanged();
    partial void Onten_loai_phongChanging(string value);
    partial void Onten_loai_phongChanged();
    partial void Ongia_phongChanging(System.Nullable<decimal> value);
    partial void Ongia_phongChanged();
    partial void Onso_nguoi_toi_daChanging(System.Nullable<int> value);
    partial void Onso_nguoi_toi_daChanged();
    #endregion
		
		public LoaiPhong()
		{
			this._Phongs = new EntitySet<Phong>(new Action<Phong>(this.attach_Phongs), new Action<Phong>(this.detach_Phongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loai_phong_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int loai_phong_id
		{
			get
			{
				return this._loai_phong_id;
			}
			set
			{
				if ((this._loai_phong_id != value))
				{
					this.Onloai_phong_idChanging(value);
					this.SendPropertyChanging();
					this._loai_phong_id = value;
					this.SendPropertyChanged("loai_phong_id");
					this.Onloai_phong_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_loai_phong", DbType="NVarChar(50)")]
		public string ten_loai_phong
		{
			get
			{
				return this._ten_loai_phong;
			}
			set
			{
				if ((this._ten_loai_phong != value))
				{
					this.Onten_loai_phongChanging(value);
					this.SendPropertyChanging();
					this._ten_loai_phong = value;
					this.SendPropertyChanged("ten_loai_phong");
					this.Onten_loai_phongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia_phong", DbType="Decimal(10,3)")]
		public System.Nullable<decimal> gia_phong
		{
			get
			{
				return this._gia_phong;
			}
			set
			{
				if ((this._gia_phong != value))
				{
					this.Ongia_phongChanging(value);
					this.SendPropertyChanging();
					this._gia_phong = value;
					this.SendPropertyChanged("gia_phong");
					this.Ongia_phongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_nguoi_toi_da", DbType="Int")]
		public System.Nullable<int> so_nguoi_toi_da
		{
			get
			{
				return this._so_nguoi_toi_da;
			}
			set
			{
				if ((this._so_nguoi_toi_da != value))
				{
					this.Onso_nguoi_toi_daChanging(value);
					this.SendPropertyChanging();
					this._so_nguoi_toi_da = value;
					this.SendPropertyChanged("so_nguoi_toi_da");
					this.Onso_nguoi_toi_daChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiPhong_Phong", Storage="_Phongs", ThisKey="loai_phong_id", OtherKey="loai_phong_id")]
		public EntitySet<Phong> Phongs
		{
			get
			{
				return this._Phongs;
			}
			set
			{
				this._Phongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Phongs(Phong entity)
		{
			this.SendPropertyChanging();
			entity.LoaiPhong = this;
		}
		
		private void detach_Phongs(Phong entity)
		{
			this.SendPropertyChanging();
			entity.LoaiPhong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NguoiDung")]
	public partial class NguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _nguoi_dung_id;
		
		private string _ten_nguoi_dung;
		
		private string _mat_khau;
		
		private bool _trang_thai;
		
		private System.Nullable<int> _vai_tro_id;
		
		private EntitySet<SinhVien> _SinhViens;
		
		private EntityRef<VaiTro> _VaiTro;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnguoi_dung_idChanging(int value);
    partial void Onnguoi_dung_idChanged();
    partial void Onten_nguoi_dungChanging(string value);
    partial void Onten_nguoi_dungChanged();
    partial void Onmat_khauChanging(string value);
    partial void Onmat_khauChanged();
    partial void Ontrang_thaiChanging(bool value);
    partial void Ontrang_thaiChanged();
    partial void Onvai_tro_idChanging(System.Nullable<int> value);
    partial void Onvai_tro_idChanged();
    #endregion
		
		public NguoiDung()
		{
			this._SinhViens = new EntitySet<SinhVien>(new Action<SinhVien>(this.attach_SinhViens), new Action<SinhVien>(this.detach_SinhViens));
			this._VaiTro = default(EntityRef<VaiTro>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoi_dung_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int nguoi_dung_id
		{
			get
			{
				return this._nguoi_dung_id;
			}
			set
			{
				if ((this._nguoi_dung_id != value))
				{
					this.Onnguoi_dung_idChanging(value);
					this.SendPropertyChanging();
					this._nguoi_dung_id = value;
					this.SendPropertyChanged("nguoi_dung_id");
					this.Onnguoi_dung_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_nguoi_dung", DbType="NVarChar(50)")]
		public string ten_nguoi_dung
		{
			get
			{
				return this._ten_nguoi_dung;
			}
			set
			{
				if ((this._ten_nguoi_dung != value))
				{
					this.Onten_nguoi_dungChanging(value);
					this.SendPropertyChanging();
					this._ten_nguoi_dung = value;
					this.SendPropertyChanged("ten_nguoi_dung");
					this.Onten_nguoi_dungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mat_khau", DbType="NVarChar(255)")]
		public string mat_khau
		{
			get
			{
				return this._mat_khau;
			}
			set
			{
				if ((this._mat_khau != value))
				{
					this.Onmat_khauChanging(value);
					this.SendPropertyChanging();
					this._mat_khau = value;
					this.SendPropertyChanged("mat_khau");
					this.Onmat_khauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trang_thai", DbType="Bit NOT NULL")]
		public bool trang_thai
		{
			get
			{
				return this._trang_thai;
			}
			set
			{
				if ((this._trang_thai != value))
				{
					this.Ontrang_thaiChanging(value);
					this.SendPropertyChanging();
					this._trang_thai = value;
					this.SendPropertyChanged("trang_thai");
					this.Ontrang_thaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vai_tro_id", DbType="Int")]
		public System.Nullable<int> vai_tro_id
		{
			get
			{
				return this._vai_tro_id;
			}
			set
			{
				if ((this._vai_tro_id != value))
				{
					if (this._VaiTro.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onvai_tro_idChanging(value);
					this.SendPropertyChanging();
					this._vai_tro_id = value;
					this.SendPropertyChanged("vai_tro_id");
					this.Onvai_tro_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_SinhVien", Storage="_SinhViens", ThisKey="nguoi_dung_id", OtherKey="nguoi_dung_id")]
		public EntitySet<SinhVien> SinhViens
		{
			get
			{
				return this._SinhViens;
			}
			set
			{
				this._SinhViens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VaiTro_NguoiDung", Storage="_VaiTro", ThisKey="vai_tro_id", OtherKey="vai_tro_id", IsForeignKey=true)]
		public VaiTro VaiTro
		{
			get
			{
				return this._VaiTro.Entity;
			}
			set
			{
				VaiTro previousValue = this._VaiTro.Entity;
				if (((previousValue != value) 
							|| (this._VaiTro.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._VaiTro.Entity = null;
						previousValue.NguoiDungs.Remove(this);
					}
					this._VaiTro.Entity = value;
					if ((value != null))
					{
						value.NguoiDungs.Add(this);
						this._vai_tro_id = value.vai_tro_id;
					}
					else
					{
						this._vai_tro_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("VaiTro");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SinhViens(SinhVien entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = this;
		}
		
		private void detach_SinhViens(SinhVien entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhanQuyen")]
	public partial class PhanQuyen
	{
		
		private System.Nullable<int> _Ma_Vai_Tro;
		
		private System.Nullable<int> _Ma_Man_Hinh;
		
		private bool _Co_Quyen;
		
		public PhanQuyen()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Vai_Tro", DbType="Int")]
		public System.Nullable<int> Ma_Vai_Tro
		{
			get
			{
				return this._Ma_Vai_Tro;
			}
			set
			{
				if ((this._Ma_Vai_Tro != value))
				{
					this._Ma_Vai_Tro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Man_Hinh", DbType="Int")]
		public System.Nullable<int> Ma_Man_Hinh
		{
			get
			{
				return this._Ma_Man_Hinh;
			}
			set
			{
				if ((this._Ma_Man_Hinh != value))
				{
					this._Ma_Man_Hinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Co_Quyen", DbType="Bit NOT NULL")]
		public bool Co_Quyen
		{
			get
			{
				return this._Co_Quyen;
			}
			set
			{
				if ((this._Co_Quyen != value))
				{
					this._Co_Quyen = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Phong")]
	public partial class Phong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _phong_id;
		
		private string _so_phong;
		
		private System.Nullable<int> _tang;
		
		private string _trang_thai;
		
		private System.Nullable<int> _loai_phong_id;
		
		private EntitySet<HoaDonDienNuoc> _HoaDonDienNuocs;
		
		private EntitySet<HopDongThuePhong> _HopDongThuePhongs;
		
		private EntitySet<SuCo> _SuCos;
		
		private EntityRef<LoaiPhong> _LoaiPhong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onphong_idChanging(int value);
    partial void Onphong_idChanged();
    partial void Onso_phongChanging(string value);
    partial void Onso_phongChanged();
    partial void OntangChanging(System.Nullable<int> value);
    partial void OntangChanged();
    partial void Ontrang_thaiChanging(string value);
    partial void Ontrang_thaiChanged();
    partial void Onloai_phong_idChanging(System.Nullable<int> value);
    partial void Onloai_phong_idChanged();
    #endregion
		
		public Phong()
		{
			this._HoaDonDienNuocs = new EntitySet<HoaDonDienNuoc>(new Action<HoaDonDienNuoc>(this.attach_HoaDonDienNuocs), new Action<HoaDonDienNuoc>(this.detach_HoaDonDienNuocs));
			this._HopDongThuePhongs = new EntitySet<HopDongThuePhong>(new Action<HopDongThuePhong>(this.attach_HopDongThuePhongs), new Action<HopDongThuePhong>(this.detach_HopDongThuePhongs));
			this._SuCos = new EntitySet<SuCo>(new Action<SuCo>(this.attach_SuCos), new Action<SuCo>(this.detach_SuCos));
			this._LoaiPhong = default(EntityRef<LoaiPhong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phong_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int phong_id
		{
			get
			{
				return this._phong_id;
			}
			set
			{
				if ((this._phong_id != value))
				{
					this.Onphong_idChanging(value);
					this.SendPropertyChanging();
					this._phong_id = value;
					this.SendPropertyChanged("phong_id");
					this.Onphong_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_phong", DbType="NVarChar(20)")]
		public string so_phong
		{
			get
			{
				return this._so_phong;
			}
			set
			{
				if ((this._so_phong != value))
				{
					this.Onso_phongChanging(value);
					this.SendPropertyChanging();
					this._so_phong = value;
					this.SendPropertyChanged("so_phong");
					this.Onso_phongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tang", DbType="Int")]
		public System.Nullable<int> tang
		{
			get
			{
				return this._tang;
			}
			set
			{
				if ((this._tang != value))
				{
					this.OntangChanging(value);
					this.SendPropertyChanging();
					this._tang = value;
					this.SendPropertyChanged("tang");
					this.OntangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trang_thai", DbType="NVarChar(50)")]
		public string trang_thai
		{
			get
			{
				return this._trang_thai;
			}
			set
			{
				if ((this._trang_thai != value))
				{
					this.Ontrang_thaiChanging(value);
					this.SendPropertyChanging();
					this._trang_thai = value;
					this.SendPropertyChanged("trang_thai");
					this.Ontrang_thaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loai_phong_id", DbType="Int")]
		public System.Nullable<int> loai_phong_id
		{
			get
			{
				return this._loai_phong_id;
			}
			set
			{
				if ((this._loai_phong_id != value))
				{
					if (this._LoaiPhong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onloai_phong_idChanging(value);
					this.SendPropertyChanging();
					this._loai_phong_id = value;
					this.SendPropertyChanged("loai_phong_id");
					this.Onloai_phong_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phong_HoaDonDienNuoc", Storage="_HoaDonDienNuocs", ThisKey="phong_id", OtherKey="phong_id")]
		public EntitySet<HoaDonDienNuoc> HoaDonDienNuocs
		{
			get
			{
				return this._HoaDonDienNuocs;
			}
			set
			{
				this._HoaDonDienNuocs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phong_HopDongThuePhong", Storage="_HopDongThuePhongs", ThisKey="phong_id", OtherKey="phong_id")]
		public EntitySet<HopDongThuePhong> HopDongThuePhongs
		{
			get
			{
				return this._HopDongThuePhongs;
			}
			set
			{
				this._HopDongThuePhongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phong_SuCo", Storage="_SuCos", ThisKey="phong_id", OtherKey="phong_id")]
		public EntitySet<SuCo> SuCos
		{
			get
			{
				return this._SuCos;
			}
			set
			{
				this._SuCos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiPhong_Phong", Storage="_LoaiPhong", ThisKey="loai_phong_id", OtherKey="loai_phong_id", IsForeignKey=true)]
		public LoaiPhong LoaiPhong
		{
			get
			{
				return this._LoaiPhong.Entity;
			}
			set
			{
				LoaiPhong previousValue = this._LoaiPhong.Entity;
				if (((previousValue != value) 
							|| (this._LoaiPhong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiPhong.Entity = null;
						previousValue.Phongs.Remove(this);
					}
					this._LoaiPhong.Entity = value;
					if ((value != null))
					{
						value.Phongs.Add(this);
						this._loai_phong_id = value.loai_phong_id;
					}
					else
					{
						this._loai_phong_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("LoaiPhong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDonDienNuocs(HoaDonDienNuoc entity)
		{
			this.SendPropertyChanging();
			entity.Phong = this;
		}
		
		private void detach_HoaDonDienNuocs(HoaDonDienNuoc entity)
		{
			this.SendPropertyChanging();
			entity.Phong = null;
		}
		
		private void attach_HopDongThuePhongs(HopDongThuePhong entity)
		{
			this.SendPropertyChanging();
			entity.Phong = this;
		}
		
		private void detach_HopDongThuePhongs(HopDongThuePhong entity)
		{
			this.SendPropertyChanging();
			entity.Phong = null;
		}
		
		private void attach_SuCos(SuCo entity)
		{
			this.SendPropertyChanging();
			entity.Phong = this;
		}
		
		private void detach_SuCos(SuCo entity)
		{
			this.SendPropertyChanging();
			entity.Phong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SinhVien")]
	public partial class SinhVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _sinh_vien_id;
		
		private System.Nullable<int> _nguoi_dung_id;
		
		private string _ma_sinh_vien;
		
		private string _ho_ten;
		
		private System.Nullable<System.DateTime> _ngay_sinh;
		
		private string _CCCD;
		
		private string _gioi_tinh;
		
		private string _so_dien_thoai;
		
		private string _dia_chi;
		
		private string _email;
		
		private string _trang_thai;
		
		private string _so_phong;
		
		private EntitySet<HopDongThuePhong> _HopDongThuePhongs;
		
		private EntityRef<NguoiDung> _NguoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsinh_vien_idChanging(int value);
    partial void Onsinh_vien_idChanged();
    partial void Onnguoi_dung_idChanging(System.Nullable<int> value);
    partial void Onnguoi_dung_idChanged();
    partial void Onma_sinh_vienChanging(string value);
    partial void Onma_sinh_vienChanged();
    partial void Onho_tenChanging(string value);
    partial void Onho_tenChanged();
    partial void Onngay_sinhChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_sinhChanged();
    partial void OnCCCDChanging(string value);
    partial void OnCCCDChanged();
    partial void Ongioi_tinhChanging(string value);
    partial void Ongioi_tinhChanged();
    partial void Onso_dien_thoaiChanging(string value);
    partial void Onso_dien_thoaiChanged();
    partial void Ondia_chiChanging(string value);
    partial void Ondia_chiChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Ontrang_thaiChanging(string value);
    partial void Ontrang_thaiChanged();
    partial void Onso_phongChanging(string value);
    partial void Onso_phongChanged();
    #endregion
		
		public SinhVien()
		{
			this._HopDongThuePhongs = new EntitySet<HopDongThuePhong>(new Action<HopDongThuePhong>(this.attach_HopDongThuePhongs), new Action<HopDongThuePhong>(this.detach_HopDongThuePhongs));
			this._NguoiDung = default(EntityRef<NguoiDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sinh_vien_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int sinh_vien_id
		{
			get
			{
				return this._sinh_vien_id;
			}
			set
			{
				if ((this._sinh_vien_id != value))
				{
					this.Onsinh_vien_idChanging(value);
					this.SendPropertyChanging();
					this._sinh_vien_id = value;
					this.SendPropertyChanged("sinh_vien_id");
					this.Onsinh_vien_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoi_dung_id", DbType="Int")]
		public System.Nullable<int> nguoi_dung_id
		{
			get
			{
				return this._nguoi_dung_id;
			}
			set
			{
				if ((this._nguoi_dung_id != value))
				{
					if (this._NguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onnguoi_dung_idChanging(value);
					this.SendPropertyChanging();
					this._nguoi_dung_id = value;
					this.SendPropertyChanged("nguoi_dung_id");
					this.Onnguoi_dung_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_sinh_vien", DbType="NVarChar(20)")]
		public string ma_sinh_vien
		{
			get
			{
				return this._ma_sinh_vien;
			}
			set
			{
				if ((this._ma_sinh_vien != value))
				{
					this.Onma_sinh_vienChanging(value);
					this.SendPropertyChanging();
					this._ma_sinh_vien = value;
					this.SendPropertyChanged("ma_sinh_vien");
					this.Onma_sinh_vienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ho_ten", DbType="NVarChar(100)")]
		public string ho_ten
		{
			get
			{
				return this._ho_ten;
			}
			set
			{
				if ((this._ho_ten != value))
				{
					this.Onho_tenChanging(value);
					this.SendPropertyChanging();
					this._ho_ten = value;
					this.SendPropertyChanged("ho_ten");
					this.Onho_tenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_sinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_sinh
		{
			get
			{
				return this._ngay_sinh;
			}
			set
			{
				if ((this._ngay_sinh != value))
				{
					this.Onngay_sinhChanging(value);
					this.SendPropertyChanging();
					this._ngay_sinh = value;
					this.SendPropertyChanged("ngay_sinh");
					this.Onngay_sinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCCD", DbType="NChar(12)")]
		public string CCCD
		{
			get
			{
				return this._CCCD;
			}
			set
			{
				if ((this._CCCD != value))
				{
					this.OnCCCDChanging(value);
					this.SendPropertyChanging();
					this._CCCD = value;
					this.SendPropertyChanged("CCCD");
					this.OnCCCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioi_tinh", DbType="NVarChar(10)")]
		public string gioi_tinh
		{
			get
			{
				return this._gioi_tinh;
			}
			set
			{
				if ((this._gioi_tinh != value))
				{
					this.Ongioi_tinhChanging(value);
					this.SendPropertyChanging();
					this._gioi_tinh = value;
					this.SendPropertyChanged("gioi_tinh");
					this.Ongioi_tinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_dien_thoai", DbType="NVarChar(20)")]
		public string so_dien_thoai
		{
			get
			{
				return this._so_dien_thoai;
			}
			set
			{
				if ((this._so_dien_thoai != value))
				{
					this.Onso_dien_thoaiChanging(value);
					this.SendPropertyChanging();
					this._so_dien_thoai = value;
					this.SendPropertyChanged("so_dien_thoai");
					this.Onso_dien_thoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dia_chi", DbType="NVarChar(MAX)")]
		public string dia_chi
		{
			get
			{
				return this._dia_chi;
			}
			set
			{
				if ((this._dia_chi != value))
				{
					this.Ondia_chiChanging(value);
					this.SendPropertyChanging();
					this._dia_chi = value;
					this.SendPropertyChanged("dia_chi");
					this.Ondia_chiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trang_thai", DbType="NVarChar(20)")]
		public string trang_thai
		{
			get
			{
				return this._trang_thai;
			}
			set
			{
				if ((this._trang_thai != value))
				{
					this.Ontrang_thaiChanging(value);
					this.SendPropertyChanging();
					this._trang_thai = value;
					this.SendPropertyChanged("trang_thai");
					this.Ontrang_thaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_phong", DbType="NVarChar(20)")]
		public string so_phong
		{
			get
			{
				return this._so_phong;
			}
			set
			{
				if ((this._so_phong != value))
				{
					this.Onso_phongChanging(value);
					this.SendPropertyChanging();
					this._so_phong = value;
					this.SendPropertyChanged("so_phong");
					this.Onso_phongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SinhVien_HopDongThuePhong", Storage="_HopDongThuePhongs", ThisKey="sinh_vien_id", OtherKey="sinh_vien_id")]
		public EntitySet<HopDongThuePhong> HopDongThuePhongs
		{
			get
			{
				return this._HopDongThuePhongs;
			}
			set
			{
				this._HopDongThuePhongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_SinhVien", Storage="_NguoiDung", ThisKey="nguoi_dung_id", OtherKey="nguoi_dung_id", IsForeignKey=true)]
		public NguoiDung NguoiDung
		{
			get
			{
				return this._NguoiDung.Entity;
			}
			set
			{
				NguoiDung previousValue = this._NguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._NguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiDung.Entity = null;
						previousValue.SinhViens.Remove(this);
					}
					this._NguoiDung.Entity = value;
					if ((value != null))
					{
						value.SinhViens.Add(this);
						this._nguoi_dung_id = value.nguoi_dung_id;
					}
					else
					{
						this._nguoi_dung_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("NguoiDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HopDongThuePhongs(HopDongThuePhong entity)
		{
			this.SendPropertyChanging();
			entity.SinhVien = this;
		}
		
		private void detach_HopDongThuePhongs(HopDongThuePhong entity)
		{
			this.SendPropertyChanging();
			entity.SinhVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SuCo")]
	public partial class SuCo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _su_co_id;
		
		private System.Nullable<int> _phong_id;
		
		private System.Nullable<System.DateTime> _ngay_bao_cao;
		
		private string _mo_ta_su_co;
		
		private string _trang_thai_xu_ly;
		
		private EntityRef<Phong> _Phong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsu_co_idChanging(int value);
    partial void Onsu_co_idChanged();
    partial void Onphong_idChanging(System.Nullable<int> value);
    partial void Onphong_idChanged();
    partial void Onngay_bao_caoChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_bao_caoChanged();
    partial void Onmo_ta_su_coChanging(string value);
    partial void Onmo_ta_su_coChanged();
    partial void Ontrang_thai_xu_lyChanging(string value);
    partial void Ontrang_thai_xu_lyChanged();
    #endregion
		
		public SuCo()
		{
			this._Phong = default(EntityRef<Phong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_su_co_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int su_co_id
		{
			get
			{
				return this._su_co_id;
			}
			set
			{
				if ((this._su_co_id != value))
				{
					this.Onsu_co_idChanging(value);
					this.SendPropertyChanging();
					this._su_co_id = value;
					this.SendPropertyChanged("su_co_id");
					this.Onsu_co_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phong_id", DbType="Int")]
		public System.Nullable<int> phong_id
		{
			get
			{
				return this._phong_id;
			}
			set
			{
				if ((this._phong_id != value))
				{
					if (this._Phong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onphong_idChanging(value);
					this.SendPropertyChanging();
					this._phong_id = value;
					this.SendPropertyChanged("phong_id");
					this.Onphong_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_bao_cao", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_bao_cao
		{
			get
			{
				return this._ngay_bao_cao;
			}
			set
			{
				if ((this._ngay_bao_cao != value))
				{
					this.Onngay_bao_caoChanging(value);
					this.SendPropertyChanging();
					this._ngay_bao_cao = value;
					this.SendPropertyChanged("ngay_bao_cao");
					this.Onngay_bao_caoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mo_ta_su_co", DbType="NVarChar(MAX)")]
		public string mo_ta_su_co
		{
			get
			{
				return this._mo_ta_su_co;
			}
			set
			{
				if ((this._mo_ta_su_co != value))
				{
					this.Onmo_ta_su_coChanging(value);
					this.SendPropertyChanging();
					this._mo_ta_su_co = value;
					this.SendPropertyChanged("mo_ta_su_co");
					this.Onmo_ta_su_coChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trang_thai_xu_ly", DbType="NVarChar(50)")]
		public string trang_thai_xu_ly
		{
			get
			{
				return this._trang_thai_xu_ly;
			}
			set
			{
				if ((this._trang_thai_xu_ly != value))
				{
					this.Ontrang_thai_xu_lyChanging(value);
					this.SendPropertyChanging();
					this._trang_thai_xu_ly = value;
					this.SendPropertyChanged("trang_thai_xu_ly");
					this.Ontrang_thai_xu_lyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phong_SuCo", Storage="_Phong", ThisKey="phong_id", OtherKey="phong_id", IsForeignKey=true)]
		public Phong Phong
		{
			get
			{
				return this._Phong.Entity;
			}
			set
			{
				Phong previousValue = this._Phong.Entity;
				if (((previousValue != value) 
							|| (this._Phong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Phong.Entity = null;
						previousValue.SuCos.Remove(this);
					}
					this._Phong.Entity = value;
					if ((value != null))
					{
						value.SuCos.Add(this);
						this._phong_id = value.phong_id;
					}
					else
					{
						this._phong_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Phong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VaiTro")]
	public partial class VaiTro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _vai_tro_id;
		
		private string _ten_vai_tro;
		
		private EntitySet<NguoiDung> _NguoiDungs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onvai_tro_idChanging(int value);
    partial void Onvai_tro_idChanged();
    partial void Onten_vai_troChanging(string value);
    partial void Onten_vai_troChanged();
    #endregion
		
		public VaiTro()
		{
			this._NguoiDungs = new EntitySet<NguoiDung>(new Action<NguoiDung>(this.attach_NguoiDungs), new Action<NguoiDung>(this.detach_NguoiDungs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vai_tro_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int vai_tro_id
		{
			get
			{
				return this._vai_tro_id;
			}
			set
			{
				if ((this._vai_tro_id != value))
				{
					this.Onvai_tro_idChanging(value);
					this.SendPropertyChanging();
					this._vai_tro_id = value;
					this.SendPropertyChanged("vai_tro_id");
					this.Onvai_tro_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_vai_tro", DbType="NVarChar(50)")]
		public string ten_vai_tro
		{
			get
			{
				return this._ten_vai_tro;
			}
			set
			{
				if ((this._ten_vai_tro != value))
				{
					this.Onten_vai_troChanging(value);
					this.SendPropertyChanging();
					this._ten_vai_tro = value;
					this.SendPropertyChanged("ten_vai_tro");
					this.Onten_vai_troChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VaiTro_NguoiDung", Storage="_NguoiDungs", ThisKey="vai_tro_id", OtherKey="vai_tro_id")]
		public EntitySet<NguoiDung> NguoiDungs
		{
			get
			{
				return this._NguoiDungs;
			}
			set
			{
				this._NguoiDungs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NguoiDungs(NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.VaiTro = this;
		}
		
		private void detach_NguoiDungs(NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.VaiTro = null;
		}
	}
}
#pragma warning restore 1591
